% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  indonesian,
]{agujournal2019}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother



\ifLuaTeX
\usepackage[bidi=basic,shorthands=off,provide=*]{babel}
\else
\usepackage[bidi=default,shorthands=off,provide=*]{babel}
\fi
\ifLuaTeX
  \usepackage{selnolig} % disable illegal ligatures
\fi


\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{url} %this package should fix any errors with URLs in refs.
\usepackage{lineno}
\usepackage[inline]{trackchanges} %for better track changes. finalnew option will compile document with changes incorporated.
\usepackage{soul}
\linenumbers
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Daftar Isi}
\else
  \newcommand\contentsname{Daftar Isi}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Daftar Gambar}
\else
  \newcommand\listfigurename{Daftar Gambar}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Daftar Tabel}
\else
  \newcommand\listtablename{Daftar Tabel}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Gambar}
\else
  \newcommand\figurename{Gambar}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabel}
\else
  \newcommand\tablename{Tabel}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Daftar}
\newcommand*\listoflistings{\listof{codelisting}{Daftar Daftar}}
\captionsetup{labelsep=period}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Kombinasi TyHbA1c Index{,} Usia{,} dan Indeks Massa Tubuh sebagai Prediktor High-Risk Plaque pada Pasien Diabetes Mellitus: Sebuah Pendekatan Nomogram Klinis},
  pdfauthor={Kadek Adit Wiryadana},
  pdflang={id},
  pdfkeywords={Indeks TyHbA1c, High-Risk Plaque, Computed Tomography
Coronary Angiography, Nomogram Klinis, Diabetes Mellitus},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}



\draftfalse

\begin{document}
\title{Kombinasi TyHbA1c Index, Usia, dan Indeks Massa Tubuh sebagai
Prediktor High-Risk Plaque pada Pasien Diabetes Mellitus: Sebuah
Pendekatan Nomogram Klinis}

\authors{Kadek Adit Wiryadana\affil{1}}
\affiliation{1}{RSUP Ngoerah, Denpasar, Indonesia}
\correspondingauthor{Kadek Adit
Wiryadana}{wiryadana.2371041012@student.unud.ac.id}


\begin{abstract}
Penyakit kardiovaskular aterosklerotik tetap menjadi penyebab utama
morbiditas dan mortalitas pada pasien Diabetes Mellitus (DM), di mana
evaluasi Computed Tomography Coronary Angiography (CTCA) dapat
mengidentifikasi High-Risk Plaque (HRP) sebagai prekursor utama sindrom
koroner akut. Penelitian ini bertujuan untuk mengevaluasi kemampuan
prediktif kombinasi Indeks TyHbA1c, Usia, Indeks Massa Tubuh (IMT), dan
status Penyakit Ginjal Kronis (PGK Stadium \(\ge\) 3) terhadap
keberadaan HRP serta mengembangkan nomogram klinis. Menggunakan desain
potong lintang (cross-sectional) pada pasien prediabetes dan DM yang
menjalani pemeriksaan CTCA di RSUP Prof.~dr. I.G.N.G. Ngoerah pada
periode 1 Januari hingga 31 Desember 2025, total 52 subjek dianalisis.
Analisis regresi logistik multivariat menunjukkan bahwa kombinasi
parameter kardiometabolik tersebut memiliki kemampuan diskriminasi yang
baik dengan nilai Area Under the Curve (AUC) sebesar 0,768. Usia dan
status komplikasi ginjal (PGK) terbukti secara statistik signifikan
meningkatkan probabilitas kerentanan plak. Model multivariat ini
berhasil dikonstruksikan ke dalam bentuk nomogram klinis yang aplikatif
untuk stratifikasi risiko secara non-invasif. Simpulannya, kombinasi
Indeks TyHbA1c, usia, IMT, dan status PGK efektif memprediksi HRP dan
dapat dimanfaatkan sebagai instrumen skoring klinis penunjang rujukan
pemeriksaan CTCA yang presisi di ruang praktik.

\textbf{Abstract} Atherosclerotic cardiovascular disease remains the
leading cause of morbidity and mortality in Diabetes Mellitus (DM)
patients, where Computed Tomography Coronary Angiography (CTCA)
evaluation identifies High-Risk Plaque (HRP) as a primary precursor of
acute coronary syndrome. This study aims to evaluate the predictive
ability of a combination of TyHbA1c Index, Age, Body Mass Index (BMI),
and Chronic Kidney Disease status (CKD Stage \(\ge\) 3) for HRP presence
and to develop a clinical nomogram. Utilizing a cross-sectional design
among prediabetes and DM patients undergoing CTCA at RSUP Ngoerah from
January 1 to December 31, 2025, a total of 52 subjects were analyzed.
Multivariate logistic regression analysis revealed that the combination
of these cardiometabolic parameters demonstrated good discriminative
performance with an Area Under the Curve (AUC) of 0.768. Age and renal
impairment status significantly increased the probability of plaque
vulnerability. This multivariate model was successfully constructed into
a clinical nomogram for non-invasive risk stratification. In conclusion,
the combination of TyHbA1c Index, age, BMI, and CKD status effectively
predicts HRP and can be utilized as a clinical scoring tool to support
precise CTCA referral practices.
\end{abstract}





\section{Pendahuluan}\label{pendahuluan}

Penyakit kardiovaskular aterosklerotik (ASCVD) tetap menjadi penyebab
utama morbiditas dan mortalitas pada pasien dengan Diabetes Mellitus
(DM). Penggunaan parameter lipid konvensional seringkali menyisakan
risiko residual yang tinggi, sehingga menuntut pencarian penanda
biologis alternatif yang mampu merepresentasikan patofisiologi
aterosklerosis secara lebih presisi. Resistensi insulin kronis diakui
sebagai motor utama pemicu disfungsi endotel dan pembentukan plak dengan
kerentanan tinggi (vulnerable plaque). Belakangan ini,
Triglyceride-Glucose (TyG) Index mulai banyak digunakan sebagai penanda
substitusi yang tervalidasi untuk menilai resistensi insulin. Kendati
demikian, penggunaan parameter glukosa darah puasa (GDP) dalam formula
TyG memiliki kelemahan mendasar akibat tingginya fluktuasi glikemik
harian. Oleh karena itu, indeks TyHbA1c---yang mengintegrasikan kadar
trigliserida dengan HbA1c---diajukan sebagai parameter yang jauh lebih
stabil dan superior dalam mencerminkan akumulasi beban
glukolipotoksisitas kronis.

Indeks TyHbA1c menawarkan pendekatan diagnostik yang menjanjikan namun
patogenesis aterosklerosis pada populasi DM bersifat multifaktorial. Hal
ini mutlak memerlukan inkorporasi dengan berbagai faktor risiko mapan
lainnya yang telah ditemukan, seperti profil lipid (kolesterol), usia
biologis, Indeks Massa Tubuh (IMT), dan khususnya status fungsi ginjal
(Penyakit Ginjal Kronis/CKD). Berbagai literatur kardiometabolik
menegaskan bahwa komplikasi nefropati diabetik bertindak sebagai
katalisator yang mempercepat progresi aterosklerosis melalui poros
kardiorenal (cardiorenal syndrome). Retensi toksin uremik, stres
oksidatif persisten, serta gangguan metabolisme mineral pada pasien
nefropati berinteraksi secara sinergis dengan kondisi
glukolipotoksisitas untuk memicu kalsifikasi medial pembuluh darah dan
degradasi stabilitas plak koroner secara masif. Kehadiran nefropati
seringkali memunculkan efek ambang batas (threshold effect) yang
melipatgandakan kerentanan vaskular melampaui efek parameter lipid atau
glikemik semata.

Saat ini pada perspektif diagnostik aterosklerotik, evaluasi anatomi
koroner non-invasif kini dapat dilakukan secara akurat menggunakan
Computed Tomography Coronary Angiography (CTCA), yang tidak hanya
menilai derajat keparahan stenosis (CAD-RADS), tetapi juga
mengidentifikasi morfologi High-Risk Plaque (HRP) sebagai prekursor
utama sindrom koroner akut. Hingga saat ini, pemodelan multivariat yang
secara holistik mengintegrasikan penanda glukolipotoksisitas novel
(TyHbA1c) bersama faktor degeneratif (Usia), adipositas viseral (IMT),
dan penanda kardiorenal (CKD) belum banyak dieksplorasi. Oleh karena
itu, penelitian ini bertujuan untuk menguji kemampuan prediktif
kombinasi parameter klinis tersebut terhadap keberadaan HRP, sekaligus
mengembangkan sebuah nomogram klinis guna memfasilitasi stratifikasi
risiko kardiovaskular secara praktis dan presisi di ruang praktik.

\section{Metode}\label{metode}

\textbf{Desain dan Populasi Penelitian}

Penelitian ini merupakan studi analitik observasional dengan pendekatan
potong lintang (\emph{cross-sectional}). Populasi target adalah seluruh
pasien yang menjalani pemeriksaan \emph{Computed Tomography Coronary
Angiography} (CTCA) di RSUP Prof.~dr. I.G.N.G. Ngoerah, Denpasar, Bali,
pada periode 1 Januari 2025 hingga 31 Desember 2025. Teknik pengambilan
sampel menggunakan \emph{consecutive sampling} hingga target sampel
terpenuhi.

Kriteria inklusi dalam penelitian ini meliputi: (1) Pasien berusia
\(\ge\) 18 tahun; (2) Memiliki rekam medis yang mencatat secara lengkap
usia, jenis kelamin, antropometri, riwayat diagnosis Diabetes Mellitus
(DM), durasi penyakit, serta riwayat penggunaan obat anti-diabetes
(OAD/Insulin) dan terapi statin; (3) Memiliki hasil laboratorium darah
yang lengkap dalam kurun waktu 30 hari dengan pemeriksaan CTCA, mencakup
profil lipid (Trigliserida, Kolesterol Total, LDL, HDL), HbA1c, dan
serum kreatinin. Sementara itu, kriteria eksklusi meliputi pasien dengan
riwayat operasi \emph{Coronary Artery Bypass Grafting} (CABG) atau
pasien dengan gagal ginjal tahap akhir (\emph{End-Stage Renal Disease}).

\textbf{Pengumpulan Data dan Definisi Operasional}

Data karakteristik demografi (Usia, Jenis Kelamin), antropometri (Indeks
Massa Tubuh/IMT), riwayat penyakit penyerta, status pengobatan, serta
parameter biokimia (HbA1c, Trigliserida, Kolesterol Total, LDL, HDL,
Kreatinin) diekstraksi dari rekam medis elektronik (SIMRS). Indeks
TyHbA1c dihitung menggunakan formula logaritma natural: TyHbA1c =
ln(Trigliserida {[}mg/dL{]} x HbA1c {[}\%{]}). Penyakit ginjal kronik
dikategorikan dari hasil fungsi ginjal hasil perhitungan CKD-EPI dan
kriteria sesuai pedoman KDIGO. Evaluasi CTCA dilakukan oleh dokter
spesialis radiologi konsultan yang tersertifikasi. Variabel dependen
utama dalam penelitian ini adalah:

1.~~~~~ \textbf{Keparahan Obstruksi Koroner:} Diklasifikasikan
berdasarkan sistem CAD-RADS 2.0, di mana kategori obstruktif signifikan
didefinisikan sebagai CAD-RADS \$\textbackslash ge\$ 3 (stenosis
\$\textbackslash ge\$ 50\%).

2.~~~~~ \textbf{Keberadaan High-Risk Plaque (HRP):} Ditetapkan sebagai
variabel biner (Ya/Tidak), yang positif apabila ditemukan minimal satu
dari empat fitur berikut pada lesi koroner: \emph{positive remodeling}
(PR), \emph{low-attenuation plaque} (LAP), \emph{spotty calcification}
(SC), atau \emph{napkin-ring sign} (NRS).

\textbf{Analisis Statistik}

Analisis data dilakukan menggunakan perangkat lunak R (R Foundation for
Statistical Computing). Variabel kontinu disajikan dalam bentuk rerata
dan simpangan baku (distribusi normal) atau median dan rentang
interkuartil (distribusi tidak normal). Analisis komparatif bivariat
dilakukan menggunakan uji \emph{Mann-Whitney U} atau \emph{Independent
T-test} untuk variabel kontinu, serta uji \emph{Chi-Square} atau
\emph{Fisher's Exact} untuk variabel kategorik.

Pemodelan prediktif dilakukan menggunakan analisis Regresi Logistik
Multivariat (\emph{Generalized Linear Model}). Berdasarkan seleksi
variabel dan patofisiologi klinis, prediktor yang dimasukkan ke dalam
model utama adalah Usia, IMT, TyHbA1c Index, dan Status CKD. Performa
diskriminatif model dievaluasi menggunakan \emph{Area Under the Curve}
(AUC) dari kurva \emph{Receiver Operating Characteristic} (ROC).
Signifikansi statistik ditetapkan pada nilai \(p < 0,05\). Berdasarkan
koefisien regresi dari model multivariat final, sebuah nomogram klinis
dikonstruksi menggunakan paket \texttt{rms} di lingkungan R untuk
memfasilitasi probabilitas prediksi personal secara visual.

\subparagraph{1. Setup}\label{setup}

\begin{verbatim}

Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    filter, lag
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union
\end{verbatim}

\begin{verbatim}
Type 'citation("pROC")' for a citation.
\end{verbatim}

\begin{verbatim}

Attaching package: 'pROC'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    cov, smooth, var
\end{verbatim}

\begin{verbatim}
Loading required package: Hmisc
\end{verbatim}

\begin{verbatim}

Attaching package: 'Hmisc'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:dplyr':

    src, summarize
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:base':

    format.pval, units
\end{verbatim}

\begin{verbatim}
-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
v forcats   1.0.1     v stringr   1.6.0
v lubridate 1.9.5     v tibble    3.3.1
v purrr     1.2.2     v tidyr     1.3.2
v readr     2.2.0     
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter()    masks stats::filter()
x dplyr::lag()       masks stats::lag()
x Hmisc::src()       masks dplyr::src()
x Hmisc::summarize() masks dplyr::summarize()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\subparagraph{2. Loading Data}\label{loading-data}

\subparagraph{3. Data Cleaning}\label{data-cleaning}

\section{Hasil}\label{hasil}

\textbf{Karakteristik Dasar dan Profil Klinis Subjek}

Penelitian ini melibatkan 52 pasien dengan diagnosis diabetes atau
prediabetes yang menjalani pemeriksaan \emph{Computed Tomography
Coronary Angiography} (CTCA) dan memenuhi kriteria inklusi. Mayoritas
subjek adalah laki-laki (n = 34; 65.4\%), dengan rentang usia rata-rata
61.04 \(\pm\) 9.9 tahun. Rerata Indeks Massa Tubuh (IMT) subjek berada
pada ambang batas \emph{overweight} (27.89 \(\pm\) 4.72 kg/m²).

Dari parameter biokimia, rata-rata kadar HbA1c subjek adalah 7.29
\(\pm\) 1.79\%, dengan kadar trigliserida 162.83 \(\pm\) 124.01 mg/dL.
Rerata nilai TyHbA1c Index pada populasi ini sebesar 6.87 \(\pm\) 0.64.
Evaluasi fungsi ginjal menunjukkan bahwa 18 pasien (34.6\%) mengalami
disfungsi ginjal (Penyakit Ginjal Kronis/CKD) dengan nilai kreatinin
serum \textgreater{} 1,2 mg/dL. Secara keseluruhan, nilai median
\emph{Global CAC Score} (kalsifikasi koroner) pada sampel adalah 300.1
(IQR: 16.8 -- 904.7) Agatston. Data karakteristik subjek ditampilkan
pada Tabel~\ref{tbl-baseline}.

\textbf{Proporsi Kemunculan \emph{High-Risk Plaque} (HRP)}

Berdasarkan evaluasi lesi koroner melalui pencitraan CTCA, proporsi
penemuan \emph{High-Risk Plaque} (HRP) terbilang tinggi. Sebanyak 37
pasien (71.2\%) teridentifikasi positif memiliki HRP, sementara 15
pasien (28.8\%) tidak menunjukkan fitur HRP.

Analisis komparatif menunjukkan bahwa pasien pada kelompok HRP (+)
memiliki usia yang secara signifikan lebih tua (63.16 \(\pm\) 9.79
tahun) dibandingkan kelompok HRP (-) (55.8 \(\pm\) 8.32 tahun). Selain
itu, derajat kalsifikasi koroner pada kelompok HRP (+) jauh lebih masif;
kelompok ini mencatatkan median skor CAC mencapai 556.7 Agatston,
berbanding sangat kontras dengan kelompok HRP (-) yang hanya memiliki
median 11.6 Agatston .

\begin{table}

\caption{\label{tbl-baseline}\textbf{Karakteristik Dasar, Profil Klinis,
dan Skor CAC Subjek Penelitian}}

\centering{

\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcccc}
\toprule
 &  & \multicolumn{3}{c}{{\textbf{Vulnerabilitas Plak (CAD-RADS)}}} \\ 
\cmidrule(lr){3-5}
\textbf{Characteristic} & \textbf{Keseluruhan}\textsuperscript{\textit{1}} & \textbf{HRP (+)}  N = 37\textsuperscript{\textit{1}} & \textbf{HRP (-)}  N = 15\textsuperscript{\textit{1}} & \textbf{p-value}\textsuperscript{\textit{2}} \\ 
\midrule\addlinespace[2.5pt]
{\bfseries Usia (Tahun)} & 61.04 ± 9.90 & 63.16 ± 9.79 & 55.80 ± 8.32 & {\bfseries 0.010} \\ 
{\bfseries Jenis Kelamin} &  &  &  & 0.8 \\ 
    L & 34 (65\%) & 25 (68\%) & 9 (60\%) &  \\ 
    P & 18 (35\%) & 12 (32\%) & 6 (40\%) &  \\ 
{\bfseries Indeks Massa Tubuh (kg/m²)} & 27.89 ± 4.72 & 27.52 ± 4.31 & 28.80 ± 5.66 & 0.4 \\ 
{\bfseries Riwayat Hipertensi} &  &  &  & 0.6 \\ 
    HT-Tidak-ada & 22 (42\%) & 17 (46\%) & 5 (33\%) &  \\ 
    HT st I & 8 (15\%) & 6 (16\%) & 2 (13\%) &  \\ 
    HT st II & 1 (1.9\%) & 1 (2.7\%) & 0 (0\%) &  \\ 
    HT Terkontrol & 21 (40\%) & 13 (35\%) & 8 (53\%) &  \\ 
{\bfseries Riwayat Merokok} &  &  &  & 0.4 \\ 
    Merokok & 20 (38\%) & 16 (43\%) & 4 (27\%) &  \\ 
    Tidak-merokok & 32 (62\%) & 21 (57\%) & 11 (73\%) &  \\ 
{\bfseries Kadar HbA1c (\%)} & 7.29 ± 1.79 & 7.37 ± 1.67 & 7.09 ± 2.09 & 0.7 \\ 
{\bfseries Trigliserida (mg/dL)} & 162.83 ± 124.01 & 142.03 ± 61.27 & 214.13 ± 205.91 & 0.2 \\ 
{\bfseries Kolesterol Total (mg/dL)} & 170.58 ± 39.96 & 162.08 ± 33.61 & 191.53 ± 47.43 & {\bfseries 0.040} \\ 
{\bfseries Kadar LDL (mg/dL)} & 107.54 ± 30.74 & 104.46 ± 28.12 & 115.13 ± 36.37 & 0.3 \\ 
{\bfseries Kadar HDL (mg/dL)} & 39.15 ± 8.82 & 39.16 ± 8.35 & 39.13 ± 10.22 & >0.9 \\ 
{\bfseries Asam Urat (mg/dL)} & 7.00 ± 2.01 & 6.85 ± 1.69 & 7.36 ± 2.67 & 0.5 \\ 
{\bfseries Kreatinin Serum (mg/dL)} & 1.51 ± 2.04 & 1.59 ± 2.27 & 1.32 ± 1.39 & 0.6 \\ 
{\bfseries Status Fungsi Ginjal} &  &  &  & 0.083 \\ 
    CKD (> 1.2) & 18 (35\%) & 16 (43\%) & 2 (13\%) &  \\ 
    Normal (<= 1.2) & 34 (65\%) & 21 (57\%) & 13 (87\%) &  \\ 
{\bfseries Indeks TyHbA1c} & 6.87 ± 0.64 & 6.83 ± 0.54 & 6.97 ± 0.86 & 0.6 \\ 
{\bfseries Global CAC Score (Agatston)} & 300.1 (16.1, 910.7) & 556.7 (219.0, 1,013.7) & 11.6 (0.0, 17.5) & {\bfseries <0.001} \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}}Mean ± SD; n (\%); Median (Q1, Q3)\\
\textsuperscript{\textit{2}}Welch Two Sample t-test; Pearson's Chi-squared test; Wilcoxon rank sum exact test\\
\end{minipage}

}

\end{table}%

\begin{verbatim}
`geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Multi_Panel_Korelasi_CAC.png}}

}

\caption{Gambar 1. Hubungan Variabel Klinis dan Metabolik terhadap
Global CAC Score Berdasarkan Status HRP}

\end{figure}%

\textbf{Analisis Multivariat Prediktor \emph{High-Risk Plaque} (HRP)}

Pemodelan regresi logistik multivariat (\emph{Generalized Linear Model})
dilakukan untuk mengevaluasi kekuatan prediktif klinis dengan memasukkan
variabel Usia, IMT, TyHbA1c Index, dan Status CKD
(Tabel~\ref{tbl-regresi}).Hasil analisis mengonfirmasi bahwa Usia
merupakan prediktor independen yang bermakna secara statistik terhadap
pembentukan plak risiko tinggi (Odds Ratio {[}OR{]} = 1.08; 95\% CI: 1
-- 1.17; \(p\) = 0.049). Secara klinis, komplikasi fungsi ginjal
memberikan dampak risiko yang paling masif; pasien dengan status CKD
menunjukkan tren peningkatan probabilitas kerentanan plak hingga 4.38
kali lipat lebih tinggi dibandingkan pasien dengan ginjal normal (OR =
4.38; 95\% CI: 0.94 -- 32.16; \(p\) = 0.087). Sementara itu, variabel
TyHbA1c Index dan IMT tidak menunjukkan kemaknaan statistik parsial
secara independen dalam model ini.

\begin{table}

\caption{\label{tbl-regresi}\textbf{Analisis Multivariat Prediktor
High-Risk Plaque (HRP)}}

\centering{

\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lccc}
\toprule
\textbf{Characteristic} & \textbf{OR} & \textbf{95\% CI} & \textbf{p-value} \\ 
\midrule\addlinespace[2.5pt]
Usia & 1.08 & 1.00, 1.17 & {\bfseries 0.039} \\ 
IMT & 1.01 & 0.88, 1.16 & >0.9 \\ 
TyHbA1c\_Index & 1.02 & 0.33, 3.31 & >0.9 \\ 
CKD\_Status & 4.38 & 0.94, 32.2 & 0.061 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
Abbreviations: CI = Confidence Interval, OR = Odds Ratio\\
\end{minipage}

}

\end{table}%

\textbf{Performa Model Prediksi dan Nomogram Klinis}

Meskipun secara parsial beberapa variabel tidak mencapai signifikansi
statistik, kombinasi holistik dari keempat parameter klinis tersebut
(Usia + IMT + TyHbA1c Index + CKD) menghasilkan daya diskriminasi
diagnostik yang solid. Analisis \emph{Receiver Operating Characteristic}
(ROC) membuktikan bahwa model multivariat ini mampu membedakan
probabilitas keberadaan HRP dengan nilai \emph{Area Under the Curve}
(AUC) sebesar 0.768. Angka diskriminasi sebesar 76.8\% ini
mengindikasikan performa model yang baik (Gambar~\ref{fig-roc}).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/figure-pdf/fig-roc-1.pdf}}

}

\caption{\label{fig-roc}\textbf{Kinerja Diskriminatif Model Prediksi
\emph{High-Risk Plaque}.} Kurva ROC dari model regresi logistik
multivariat yang mengintegrasikan Usia, Indeks Massa Tubuh (IMT),
TyHbA1c Index, dan Status Penyakit Ginjal Kronis (CKD). Model ini
menunjukkan tingkat akurasi diagnostik yang baik dengan nilai \emph{Area
Under the Curve} (AUC) sebesar 0,768.}

\end{figure}%

Model ini kemudian ditransformasikan secara visual ke dalam bentuk
nomogram klinis guna memfasilitasi estimasi probabilitas kemunculan
\emph{vulnerable plaque} (0 - 100\%) secara personal dan praktis bagi
masing-masing pasien di ruang praktik.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/figure-pdf/fig-nomogram-1.pdf}}

}

\caption{\label{fig-nomogram}\textbf{Nomogram Klinis untuk Prediksi
Probabilitas \emph{High-Risk Plaque} (HRP).} Alat stratifikasi risiko
yang dikembangkan dari pemodelan regresi logistik multivariat.
Probabilitas individual pasien diproyeksikan pada aksis terbawah dengan
menjumlahkan total poin (0-100) dari keempat variabel prediktor: Usia,
IMT, Indeks TyHbA1c, dan Status CKD.}

\end{figure}%

\section{Pembahasan}\label{pembahasan}

Penelitian ini mengevaluasi nilai prediktif dari kombinasi parameter
klinis dan kardiometabolik---yang mencakup Usia, Indeks Massa Tubuh
(IMT), Indeks TyHbA1c, dan status Penyakit Ginjal Kronis (PGK Stadium
\(\ge\) 3)---terhadap keparahan penyakit arteri koroner dan kerentanan
plak pada 52 pasien diabetes serta prediabetes yang menjalani
pemeriksaan \emph{Computed Tomography Coronary Angiography} (CTCA).
Temuan utama dari studi ini menunjukkan bahwa pemodelan regresi logistik
multivariat yang mengintegrasikan parameter-parameter tersebut memiliki
kemampuan diskriminatif yang baik dalam memprediksi keberadaan
\emph{High-Risk Plaque} (HRP) dengan nilai \emph{Area Under the Curve}
(AUC) mencapai \textbf{0.768} (atau 76.8\%).

\textbf{Glukolipotoksisitas Kronis, Aktivasi Makrofag, dan Kerentanan
Plak (\emph{Plaque Vulnerability})}

Keunggulan prediktif dari model ini terhadap keberadaan HRP memberikan
wawasan patofisiologis yang krusial. HRP---yang bermanifestasi sebagai
\emph{positive remodeling}, kalsifikasi bercak (\emph{spotty
calcification}), dan \emph{low-attenuation plaque}---merupakan lesi
prekursor struktural yang sangat rentan mengalami ruptur dan memicu
sindrom koroner akut. Dalam studi ini, Indeks TyHbA1c diajukan sebagai
penanda \emph{novel} yang merepresentasikan interaksi ganda antara
dislipidemia aterogenik (hipertrigliseridemia) dan paparan hiperglikemia
kronis (HbA1c). Secara biomolekuler, kondisi glukolipotoksisitas
persisten memicu akumulasi \emph{Advanced Glycation End-products} (AGEs)
dan \emph{Reactive Oxygen Species} (ROS) yang merusak integritas
endotel, memfasilitasi infiltrasi makrofag besar-besaran yang
bertransformasi menjadi sel busa (\emph{foam cells}) di ruang
subendotel.

Berdasarkan patobiologi vaskular, makrofag intratunika yang teraktivasi
ini mensekresi enzim \emph{Matrix Metalloproteinases} (terutama MMP-2
dan MMP-9) secara masif yang mendegradasi matriks ekstraseluler pada
tunika media. Degradasi matriks ke arah luar dinding epikardial inilah
yang mendasari fenomena \emph{positive remodeling} (Fenomena Glagov)
sebagai upaya kompensatorik tubuh mempertahankan ukuran lumen. Meskipun
secara hemodinamik aliran darah awal tampak tidak terganggu, remodeling
ini memfasilitasi pembentukan plak dengan inti nekrotik lipid masif dan
selubung fibrosa tipis (\emph{Thin-Cap Fibroatheroma} / TCFA). Hal ini
menjelaskan mengapa indeks TyHbA1c dan parameter kardiometabolik lebih
unggul dalam mencerminkan ``kualitas'' dan kerentanan plak (HRP)
dibandingkan sekadar mengevaluasi ``kuantitas'' persentase penyumbatan
lumen konvensional.

\textbf{Peran Dominan Usia dan Poros Kardiorenal}

Dalam pemodelan multivariat, usia muncul sebagai prediktor independen
yang konsisten dan bermakna secara statistik (OR = 1.08, \(p\) = 0.049).
Proses aterosklerosis pada dasarnya adalah patologi kumulatif yang
bergantung pada waktu (\emph{time-dependent}), di mana durasi paparan
faktor risiko glukometabolik pada sel endotel memperbesar probabilitas
degenerasi vaskular.

Selain faktor usia, temuan penting dalam studi ini menyoroti
signifikansi klinis komplikasi ginjal. Kehadiran Penyakit Ginjal Kronis
(PGK Stadium \(\ge\) 3) terbukti memberikan tren peningkatan risiko
kerentanan plak yang masif hingga \textbf{4.38 kali lipat} dibanding
fungsi ginjal normal. Secara patofisiologis, nefropati diabetik
bertindak sebagai katalisator melalui poros kardiorenal
(\emph{cardiorenal syndrome}). Retensi toksin uremik, stres oksidatif
sistemik, serta gangguan metabolisme mineral pada pasien PGK
berinteraksi secara sinergis dengan glukolipotoksisitas untuk memicu
kalsifikasi medial pembuluh darah (\emph{Medial Arterial Calcification})
secara agresif, melampaui dampak dari gangguan metabolik semata.

\textbf{Implikasi Klinis dan Pembuatan Nomogram}

Kemampuan diskriminasi diagnostik model yang mencapai AUC 0.768
menawarkan implikasi translasi klinis yang bernilai tinggi. Seluruh
parameter pembentuk model (Usia, IMT, Indeks TyHbA1c, dan status PGK)
bersumber dari pemeriksaan rutin yang murah, objektif, dan non-invasif.
Melalui konversi model matematis ini menjadi bentuk instrumen visual
berupa nomogram klinis, para klinisi dimampukan untuk melakukan
stratifikasi risiko kardiovaskular secara cepat dan personal di ruang
praktik. Pendekatan ini memfasilitasi \emph{decision making} untuk
menyeleksi pasien asimptomatik yang paling membutuhkan rujukan prioritas
pemeriksaan CTCA maupun eskalasi terapi kardioprotektif.

\textbf{Keterbatasan Penelitian}

Studi ini memiliki beberapa keterbatasan yang perlu dicatat. Desain
potong lintang (\emph{cross-sectional}) membatasi kemampuan studi untuk
menyimpulkan hubungan kausalitas sejati secara longitudinal. Selain itu,
ukuran sampel pada kohort \emph{single-center} ini masih memerlukan
ekspansi lebih lanjut guna memperkuat interval kepercayaan
(\emph{confidence interval}) pada beberapa variabel prediktor sekunder.
Penelitian lanjutan dengan validasi kohort eksternal multisentris sangat
disarankan guna mengonfirmasi keandalan serta kalibrasi dari nomogram
klinis yang dihasilkan.

\section{Simpulan}\label{simpulan}

Kombinasi parameter klinis dan kardiometabolik yang mencakup usia,
Indeks Massa Tubuh (IMT), Indeks TyHbA1c, dan status Penyakit Ginjal
Kronis (PGK Stadium \(\ge\) 3) memiliki kemampuan diskriminasi
diagnostik yang baik dalam memprediksi keberadaan \emph{High-Risk
Plaque} (HRP) pada pasien prediabetes dan diabetes mellitus. Indeks
TyHbA1c sebagai representasi beban glukolipotoksisitas kronis, yang
disandingkan dengan faktor degeneratif usia dan komplikasi nefropati
melalui poros kardiorenal, terbukti superior dalam mencerminkan
kerentanan struktural plak koroner (\emph{vulnerable plaque})
dibandingkan parameter lipid konvensional semata. Pemodelan multivariat
ini berhasil dikonstruksikan ke dalam bentuk nomogram klinis yang
aplikatif untuk membantu para klinisi melakukan stratifikasi risiko
kardiovaskular secara non-invasif, guna menyeleksi prioritas rujukan
pemeriksaan \emph{Computed Tomography Coronary Angiography} (CTCA)
secara lebih dini dan presisi di ruang praktik.

\section{Daftar Pustaka}\label{daftar-pustaka}




\end{document}
